'use strict';
const languageStrings = {
    'en-GB': {
        'translation': {
            'WELCOME_MESSAGE' : 'Welcome to Text Adapter Skill. <break time="500ms"/> Login with your name to start',
            'REP_WELCOME':'Login with your name to start',
            'LEAVE_MESSAGE':'Goodbye. See you soon',
            'LEAVE_MESSAGE_2':'An error occurred that caused the session to end. See you soon',
            'STOP_MESSAGE':'Okay, what do you want to do now?',
            'REP_STOP':'Are you there? What we do now?',
            'REGISTER_SUC_MESSAGE':'Great! Could be successfully registered with the username {{slotValue}}',
            'REGISTER_REJ_MESSAGE':'Sorry, the user already exists. It is not possible to register with the username {{slotValue}}. <break time="1s"/> Please, Register with a new name',
            'REP_REGISTER_REJ_MESSAGE': 'Please, register with a new name',
            'LOGIN_SUC_MESSAGE':'Hello {{slotValue}}! <break time="1s"/> ',
            'REP_LOGIN_SUC_MESSAGE':'If you want to listen your contents, you must to say {{message}}',
            'LOGIN_REJ_MESSAGE':'Sorry, there is no registered user with the name {{slotValue}}. <break time="1s"/> Please log in with a valid username.',
            'REP_LOGIN_REJ_MESSAGE':'Please, log in with a valid username',
            'LOGIN_REJ2_MESSAGE':'Sorry, you can not login because the user {{slotValue}} is already active in the system.',
            'REP_LOGIN_REJ2_MESSAGE':'Please, go back later',
            'LOGOUT_SUC_MESSAGE':'Goodbye {{slotValue}}. See you later!',
            'LOGOUT_REJ_MESSAGE':'Sorry, you can not close the session. <break time="1s"/> The active user in the system is {{slotValue}} . <break time="1s"/> Please, enter a correct username',
            'REP_LOGOUT_REJ_MESSAGE':'Please, enter a correct username',
            'LOGOUT_REJ2_MESSAGE':'Sorry, you must first login before you can logout',
            'CONTENT_REJ_MESSAGE':'Sorry, first you must login to be able to get news',
            'REP_CONTENT_REJ_MESSAGE':'Please login before you can obtain the content',
            'CONTENT_REJ2_MESSAGE':'Sorry, I didn\'t get that. Here you must to say: {{message}}',
            'REP_CONTENT_REJ2_MESSAGE':'Please enter a valid intent request. You can say {{message}}',
            'LIST_OF_TITLES':'Say ok to confirm and next to pass to the next title. <break time="500ms"/> {{metainfo}} <break time="500ms"/> {{title}} <break time="500ms"/> is from: {{url}}.',
            'LIST_OF_CATEGORIES':'Say ok to confirm and say next to pass to the next category. <break time="1s"/> The categories are: {{category}}',
            'OBTAIN_SLOT':'Great! <break time="500ms"/> Which is your username?',
            'REP_OBTAIN_SLOT':'Please say your username',
            'LAST_CONTENT':'This is the last content. ',
            'LAST_CONTENT_END':'Say next to return to the list',
            'START_POINT':'There are no more categories. Say return my categories to return to the list or sign off before to quit',
            'ASK_FOR_INTRO':'Do you like to listen a intro before?',
            'READ_INTRO':'{{intro}}. <break time="1s"/> Do you want to listen the rest of the content?',
            'UNHANDLED':' yes or no',
            'READ_OPTIONS':'Your options are {{options}}',        
            'CONECTOR':' or ',
            'SEARCH_MSG':'We are searching in the system.',
            'READ_TITLE':'<break time="400ms"/> {{metainfo}} <break time="500ms"/> {{title}} <break time="500ms"/> is from: {{url}} ',
            'READ_OP':'Do you want to listen your flows of contents <break time="300ms"/> or the contents filtered by categories?',
            'REPROMPT_TEXT':"What do you want to do now?",
            'CONFIRM_SLOT':"You want to register with the name {{user}}?",
            'CONFIRM_SLOT_REP':"Okay, which is your username?",
            'ERROR_GET_TITLE':"<break time='4s'/> We couldn't recognize the desired content. Please say next to pass to the next title",
            'START_SPEECH':"The text is: ",
            'START_POINT_2':"There are no more flows of contents. Say return my flows to return to the list or sign off before to quit",
            'CONTENT_END': ' Say next to pass to the next title or back to return', 
            'CONTENTS_READY':'Do you want to listen the list of titles?',
            'TIMEOUT':"The time to get the contents is exceeded. Please try again",
            'XPATH_CHANGED':"The content is not available because the path to the resource in the page {{url}} were changed. Say next to continue ",
            'XPATH_CHANGED_LAST':'This is the last content in the flow. <break time="500ms"/> The content is not available because the path to the resource in the page {{url}} were changed. Say next to continue ',
            'CONTENTS_NOT_READY':"The contents are not ready yet. We try to get them again. Please say next to continue",
            'CONTENTS_READY_PATTERN':'You chosen the pattern to {{pattern}}. <break time="300ms"/> Do you want to listen the list of titles?',
            'NEXT_READ':'Say next to pass to the next title <break time="400ms"/> {{Metainfo}} <break time="1s"/> {{title}} <break time="500ms"/> is from <break time="1s"/> {{url}}',
            'PREV_METAINFO':'This is the last content. '
        }
    },
    'en-US': {
        'translation': {
            'WELCOME_MESSAGE' : 'Welcome to Text Adapter Skill. <break time="500ms"/> Login with your name to start',
            'REP_WELCOME':'Login with your name to start',
            'LEAVE_MESSAGE':'Goodbye. See you soon',
            'LEAVE_MESSAGE_2':'An error occurred that caused the session to end. See you soon',
            'STOP_MESSAGE':'Okay, what do you want to do now?',
            'REP_STOP':'Are you there? What we do now?',
            'REGISTER_SUC_MESSAGE':'Great! Could be successfully registered with the username {{slotValue}}',
            'REGISTER_REJ_MESSAGE':'Sorry, the user already exists. It is not possible to register with the username {{slotValue}}. <break time="1s"/> Please, Register with a new name',
            'REP_REGISTER_REJ_MESSAGE': 'Please, register with a new name',
            'LOGIN_SUC_MESSAGE':'Hello {{slotValue}}! <break time="1s"/>',
            'REP_LOGIN_SUC_MESSAGE':'If you want to listen your contents, you must to say {{message}}',
            'LOGIN_REJ_MESSAGE':'Sorry, there is no registered user with the name {{slotValue}}. <break time="1s"/> Please log in with a valid username.',
            'REP_LOGIN_REJ_MESSAGE':'Please, log in with a valid username',
            'LOGIN_REJ2_MESSAGE':'Sorry, you can not login because the user {{slotValue}} is already active in the system.',
            'REP_LOGIN_REJ2_MESSAGE':'Please, go back later',
            'LOGOUT_SUC_MESSAGE':'Goodbye {{slotValue}}. See you later!',
            'LOGOUT_REJ_MESSAGE':'Sorry, you can not close the session. <break time="1s"/> The active user in the system is {{slotValue}} . <break time="1s"/> Please, enter a correct username',
            'REP_LOGOUT_REJ_MESSAGE':'Please, enter a correct username',
            'LOGOUT_REJ2_MESSAGE':'Sorry, you must first login before you can logout',
            'CONTENT_REJ_MESSAGE':'Sorry, first you must login to be able to get news',
            'REP_CONTENT_REJ_MESSAGE':'Please login before you can obtain the content',
            'CONTENT_REJ2_MESSAGE':'Sorry, I didn\'t get that. Here you must to say: {{message}}',
            'REP_CONTENT_REJ2_MESSAGE':'Please enter a valid intent request. You can say {{message}}',
            'LIST_OF_TITLES':'Say ok to confirm and next to pass to the next title. <break time="500ms"/> {{metainfo}} <break time="500ms"/> {{title}} <break time="500ms"/> is from: {{url}}.',
            'LIST_OF_CATEGORIES':'Say ok to confirm and say next to pass to the next category. <break time="500ms"/> The categories are: {{category}}',
            'LIST_OF_SETS':'Say ok to confirm and say next to pass to the next flow of contents. <break time="500ms"/> The flows are: {{conjunto}}',            
            'OBTAIN_SLOT':'Great! <break time="500ms"/> Which is your username?',
            'REP_OBTAIN_SLOT':'Please say your username',
            'LAST_CONTENT':'This is the last content',
            'LAST_CONTENT_END':'Say next to return to the list',
            'START_POINT':'There are no more categories. Say return my categories to return to the list or sign off before to quit',
            'ASK_FOR_INTRO':'Do you like to listen a intro before?',
            'READ_INTRO':'{{intro}}. <break time="1s"/> Do you want to listen the rest of the content?',
            'UNHANDLED':' yes or no',
            'READ_OPTIONS':'Your options are: {{options}}',
            'CONECTOR':' or ',
            'SEARCH_MSG':'We are searching in the system',
            'READ_TITLE':'<break time="400ms"/> {{metainfo}} <break time="500ms"/> {{title}} <break time="500ms"/> is from: {{url}} ',
            'READ_OP':'Do you want to listen your flows of contents <break time="300ms"/> or the contents filtered by categories?',
            'REPROMPT_TEXT':"What do you want to do now?",
            'CONFIRM_SLOT':"You want to register with the name {{user}}?",
            'CONFIRM_SLOT_REP':"Okay, which is your username?",
            'ERROR_GET_TITLE':"<break time='4s'/> We couldn't recognize the desired content. Please say next to pass to the next title",
            'START_SPEECH':"The text is: ",
            'START_POINT_2':"There are no more flows of contents. Say return my flows to return to the list or sign off before to quit",
            'CONTENT_END': ' Say next to pass to the next title or back to return', 
            'CONTENTS_READY':' Your contents are ready. Do you want to listen the list of titles?',
            'TIMEOUT':"The time to get the contents is exceeded. Please try again",
            'XPATH_CHANGED':"The content is not available because the path to the resource in the page {{url}} were changed. Say next to continue ",
            'XPATH_CHANGED_LAST':'This is the last content in the flow. <break time="500ms"/> The content is not available because the path to the resource in the page {{url}} were changed. Say next to continue ',
            'CONTENTS_NOT_READY':"The contents are not ready yet. We try to get them again. Please say next to continue",
            'CONTENTS_READY_PATTERN':'You chosen the pattern to {{pattern}}. <break time="300ms"/> Do you want to listen the list of titles?',
            'NEXT_READ':'Say next to pass to the next title <break time="400ms"/> {{Metainfo}} <break time="1s"/> {{title}} <break time="500ms"/> is from <break time="1s"/> {{url}}',
            'PREV_METAINFO':'This is the last content. '
        }
    },
    'es-ES': {
        'translation': {
            'WELCOME_MESSAGE' : 'Bienvenido al skill Lector de contenidos. Ingresa con tu nombre para empezar',
            'REP_WELCOME':'Ingresa con tu nombre para empezar',
            'LEAVE_MESSAGE':'Adios. Nos vemos pronto',
            'LEAVE_MESSAGE_2':'Se cerro la sesion debido a un error producido. Nos vemos pronto',
            'STOP_MESSAGE':'Ok, que quieres hacer ahora?',
            'REP_STOP':'Estas ahi? Que hacemos ahora?',
            'REGISTER_SUC_MESSAGE':'Genial! Te pudiste registrar con el nombre {{slotValue}}',
            'REGISTER_REJ_MESSAGE':'Lo siento, el usuario ya existe. No es posible registrarte con el nombre {{slotValue}}. Registrate con un nuevo nombre',
            'REP_REGISTER_REJ_MESSAGE': 'Por favor, registrate con un nuevo nombre',
            'LOGIN_SUC_MESSAGE':'Hola {{slotValue}}! <break time="1s"/>',
            'REP_LOGIN_SUC_MESSAGE':'Si quieres escuchar tus contenidos, solo di {{message}}',
            'LOGIN_REJ_MESSAGE':'Lo siento, no existe ningun usuario registrado con el nombre {{slotValue}}. Ingresa con un nombre de usuario valido',
            'REP_LOGIN_REJ_MESSAGE':'Por favor, ingresa con un nombre de usuario valido',
            'LOGIN_REJ2_MESSAGE':'Lo siento, no puedes ingresar porque el usuario {{slotValue}} ya se encuentra activo',
            'REP_LOGIN_REJ2_MESSAGE':'Por favor, vuelve mas tarde',
            'LOGOUT_SUC_MESSAGE':'Adios {{slotValue}}. Nos vemos mas tarde!',
            'LOGOUT_REJ_MESSAGE':'Lo siento, no es posible cerrar la sesion. Ingresa un nombre de usuario correcto. El usuario activo en el sistema es {{slotValue}}',
            'REP_LOGOUT_REJ_MESSAGE':'Por favor, ingresa con un nombre de usuario correcto',
            'LOGOUT_REJ2_MESSAGE':'Lo siento, debes ingresar primero al sistema antes de poder salir',
            'CONTENT_REJ_MESSAGE':'Lo siento, debes ingresar primero para poder obtener tus contenidos',
            'REP_CONTENT_REJ_MESSAGE':'Por favor ingresa antes de poder obtener tus contenidos',
            'CONTENT_REJ2_MESSAGE':'Lo siento, tienes que decir {{message}} ',
            'REP_CONTENT_REJ2_MESSAGE':'Por favor ingresa un requerimiento correcto. Puede decir {{message}}',
            'LIST_OF_TITLES':'Aqui tienes las noticias del momento. <break time="400ms"/> {{title}} <break time="500ms"/> es de: {{url}} . <break time="500ms"/> Quieres escuchar una introduccion de la noticia? ',
            'LIST_OF_CATEGORIES':'Indica ok para confirmar y siguiente para avanzar a la siguiente categoria. <break time="500ms"/> Las categorias son: {{category}}',
            'LIST_OF_SETS':'Indica ok para confirmar y siguiente para avanzar al siguiente grupo. <break time="500ms"/> Los grupos son: {{conjunto}}',
            'OBTAIN_SLOT':'Genial! <break time="500ms"/> Cual es tu usuario?',
            'REP_OBTAIN_SLOT':'Por favor indica tu nombre de usuario',
            'LAST_CONTENT':'Este es el ultimo contenido.',        
            'LAST_CONTENT_END':'Indica siguiente para volver a la lista',
            'START_POINT':'No quedan mas categorias. Indica retornar mis categorias para volver a la lista o cierra sesion antes de salir',
            'ASK_FOR_INTRO':'Quieres escuchar una introduccion antes?',
            'READ_INTRO':'{{intro}}. <break time="500ms"/> {{mge}}',
            'UNHANDLED':' si o no',
            'READ_OPTIONS':'Puedes decir {{options}}',
            'CONECTOR':' o ',
            'SEARCH_MSG':'Estamos buscando en el sistema',
            'READ_TITLE':'{{metainfo}} <break time="400ms"/> {{title}} <break time="500ms"/> es de {{url}} .<break time="500ms"/> Quieres escuchar una introduccion? ', //Puede cambiar el mensaje             
            'READ_TITLE_2':'{{metainfo}} <break time="500ms"/> {{title}} grados', //Puede cambiar el mensaje             
            'READ_OP':'Quieres escuchar tus grupos de contenidos <break time="300ms"/> o los contenidos filtrados por categorias?',
            'REPROMPT_TEXT':"Que quieres hacer ahora?",
            'CONFIRM_SLOT':"Quieres registrarte con el nombre {{user}}?",
            'CONFIRM_SLOT_REP':"Bueno. Cual es tu usuario?",
            'ERROR_GET_TITLE':"<break time='4s'/> No pudimos reconocer el contenido. Por favor, indica siguiente para obtener un nuevo titulo",
            'START_SPEECH':"El texto es: ",
            'START_POINT_2':"No quedan mas grupos de contenidos. Indica leer mis grupos para volver a la lista o cierra sesion antes de salir",
            'CONTENT_END': "Indica siguiente para pasar al proximo titulo o volver atras para retornar", 
            'CONTENTS_READY':"Tus contenidos están listos. Quieres escuchar la lista de titulos?",
            'TIMEOUT':"Se excedió el tiempo para obtener los contenidos. Por favor, intente de nuevo",
            'XPATH_CHANGED':"El contenido no esta disponible porque la ruta al recurso en la pagina {{url}} ha cambiado. Indica siguiente para continuar ",
            'XPATH_CHANGED_LAST':'Este es el ultimo contenido en el grupo.<break time="500ms"/> El contenido no esta disponible porque la ruta al recurso en la pagina {{url}} ha cambiado. Indica siguiente para continuar ',
            'CONTENTS_NOT_READY':"El contenido del sitio {{url}} todavía no se encuentra disponible. Por favor, di intentar de nuevo para continuar ",
            'CONTENTS_READY_PATTERN':'Tu listado de noticias esta listo. Quieres escuchar los titulos?',//'Has escogido el patron para {{pattern}}.<break time="300ms"/> Quieres escuchar el listado de titulos?',
            'NEXT_READ':'Los datos se obtienen del sitio {{url}}. <break time="500ms"/> Ahora en La Plata tenemos una temperatura de {{title}} grados. Quieres obtener mas informacion?',
            'PREV_METAINFO':'Este es el ultimo contenido. '
        }
    }
};

module.exports = languageStrings